version: "3.1"
services:
    app:
        build: .
        env_file:
            - .env
        ports:
            - 3003:80
    server:
        image: node
        env_file:
            - .env
        ports:
            - 3002:3002
        working_dir: /usr/src/app
        command: bash -c "npm install && npm run start-backend"
        volumes:
            - ./:/usr/src/app
        depends_on:
            - db
    db:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./mysql_data:/var/lib/mysql
            - ./create-database.sql/:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 3306:3306